### ISSUE TITLE
storm-extract lists no files for HotS Tracer patch (OS X 10.11.4)

### ISSUE THREAD

**Issue by jordancurve** [jnovack/storm-extract#3]
storm-extract lists no files for HotS Tracer patch (OS X 10.11.4):

```
$ ./storm-extract -f / 
Searching for files: 
  0 files found.

$ ls "/Applications/Heroes of the Storm/"
Heroes of the Storm.app
HeroesData
Launcher.db
Support
Versions
```

**Comment by jnovack** [comment]
Documentation issue.  Try `storm-extract -f .`

Should find 180760 files (before today's patch)

The `-f` searches filenames, and there's no slashes in fileNAMES.  #willfix
