### ISSUE TITLE
storm-extract command-line fails on latest PTR version (42898)

### ISSUE THREAD

**Issue by Pspsully** [jnovack/storm-extract#4]
I know you're not crazy with working on PTR patches :) But just incase this feeds into live in a couple of weeks, storm-extract (command line) is not working on the latest PTR patch (worked fine on the previous one earlier in the week).

Error message is: 

> Assertion failed: (pVarBlob->pbData == NULL), function LoadInfoVariable, file /Users/username/storm-extract/CascLib/src/CascFiles.cpp, line 257.
> Abort trap: 6

heroes-json extracts fine on the same patch (extracts, fails to make json due to a couple of eval issues)

I re-made storm-extract with lines 257 & 258 (sanity checks) commented out and working fine again but not sure what they are sanity checking or what issues that causes :)

Again, I know it's PTR so feel free to close if you don't think it will be an issue on live.

**Comment by jnovack** [comment]
That's an issue with the upstream code, not mine. :/

I will see if he has an update or if it's really an issue with Live.

Thank you.

**Comment by herrvigg** [comment]
yes i noticed that issue too and it's still the case. Well actually in my case, it's the opposite, it works on the PTR version (Valeera) but not the live EU version (Zul'jin 22.6) !

But the reason is most likely the same. It seems to be something it doesn't expect from the .build.info. Have to check better.

**Comment by jnovack** [comment]
Try updating the upstream code.  If that works, please submit a pull request.

```
cd CascLib
git checkout master
git pull
```
