### ISSUE TITLE
0-length files being extracted

### ISSUE THREAD

**Issue by madelynnblue** [jnovack/storm-extract#8]
`storm-extract -i hots -t dds -s mods/heroes.stormmod/base.stormassets/Assets/Textures -f storm_ui_icon_alexstrasza_abundance.dds -x -v`

Results in a 0 length file on the current Heroes of the Storm data from today's patch (2.29.1). The previous patch (2.29.0) worked fine. Only some files, from some new changes, are being extracted with 0 length.

**Comment by madelynnblue** [comment]
Guess it was just my computer bein weird. Nevermind.

**Comment by jnovack** [comment]
As CascLib updates, you may also wish to try `$ git submodule update` occasionally.
